export enum TRADINGVIEW_ENTRY_EXIT_SIGNAL {
    LONG_ENTRY = 'LONG_ENTRY',
    SHORT_ENTRY = 'SHORT_ENTRY',
    LONG_EXIT = 'LONG_EXIT',
    SHORT_EXIT = 'SHORT_EXIT',
    BULLISH = 'BULLISH',
    BEARISH = 'BEARISH'
}

export enum TRADINGVIEW_TREND {
    UP = 'UP',
    DOWN = 'DOWN'
}
